[tasks.item0]
meter = shape
meterStyle = tasks.control.item
y = 47
[tasks.item0.text]
meter = string
meterStyle = tasks.control.item.text
text = do a thing
[tasks.item1]
meter = shape
meterStyle = tasks.control.item
[tasks.item1.text]
meter = string
meterStyle = tasks.control.item.text
text = fish for pp
[tasks.item2]
meter = shape
meterStyle = tasks.control.item
completed = fill color 0, 0, 0
[tasks.item2.text]
meter = string
meterStyle = tasks.control.item.text
text = clone nxtos
[tasks.item3]
meter = shape
meterStyle = tasks.control.item
[tasks.item3.text]
meter = string
meterStyle = tasks.control.item.text
text = poob

